[project]
name = "thermoprop"
version = "0.2.0"
description = "A Python thermodynamic property wrapper for real fluids, ideal gases, and liquid rocket propellants."
readme = "README.md"
license = "GPL-3.0-only"
authors = [
    { name = "Saaketh Ramoju", email = "skramoju@gmail.com" }
]
requires-python = ">=3.11"
keywords = [
    "thermodynamics",
    "coolprop",
    "pyromat",
    "rocketprops",
    "fluids",
    "ideal-gas",
    "propellants",
    "thermophysical-properties",
    "engineering",
    "rocket-propulsion",
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Education",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Physics",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
    "Operating System :: OS Independent",
]
dependencies = [
    "coolprop>=6.8.0",
    "numpy>=2.4.6",
    "pyromat>=2.2.6",
    "rocketprops>=0.1.8",
    "scipy>=1.17.1",
]

[project.urls]
Homepage = "https://github.com/saakethramoju/ThermoProp"
Repository = "https://github.com/saakethramoju/ThermoProp"
Issues = "https://github.com/saakethramoju/ThermoProp/issues"
Changelog = "https://github.com/saakethramoju/ThermoProp/blob/main/CHANGELOG.md"

[build-system]
requires = ["uv_build>=0.11.18,<0.12.0"]
build-backend = "uv_build"